let eventSource=null,reconnectTimer=null,pollTimer=null,activeTab=false,pendingCheckInFlight=false,contextDead=false,observer=null;
const processing=new Set();
function fromB64url(value){const s=String(value||'').replace(/-/g,'+').replace(/_/g,'/')+'='.repeat((4-(String(value||'').length%4))%4);const raw=atob(s);return Uint8Array.from(raw,c=>c.charCodeAt(0));}
function fromBase64(value){const raw=atob(value);const out=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)out[i]=raw.charCodeAt(i);return out.buffer;}
function sleep(ms){return new Promise(r=>setTimeout(r,ms));}
function runtimeMessage(message){return new Promise((resolve,reject)=>{if(contextDead){reject(new Error('Extension context invalidated. Refresh the ChatGPT tab.'));return}try{chrome.runtime.sendMessage(message,response=>{if(chrome.runtime.lastError){const msg=chrome.runtime.lastError.message||'Extension context invalidated.';if(/context invalidated|receiving end does not exist/i.test(msg)){contextDead=true;cleanup();}reject(new Error(msg));}else resolve(response);});}catch(e){if(/context invalidated/i.test(e?.message||'')){contextDead=true;cleanup();}reject(e);}});}
async function getConfig(){return chrome.storage.local.get({baseUrl:'',pairCode:'',privateKey:null,enabled:true});}
function isCurrentChat(){return !contextDead&&activeTab&&document.visibilityState==='visible'&&(location.hostname.endsWith('chatgpt.com')||location.hostname.endsWith('openai.com'));}
function visible(el){return !!el&&el.getClientRects().length>0&&getComputedStyle(el).visibility!=='hidden'&&getComputedStyle(el).display!=='none';}
async function findUploadInput(){let inputs=[...document.querySelectorAll('input[type=file]')];let input=inputs.find(e=>{const a=(e.getAttribute('accept')||'').toLowerCase();return !a||a.includes('image')||a.includes('*');});if(input)return input;const buttons=[...document.querySelectorAll('button,[role=button]')].filter(visible);const btn=buttons.find(b=>{const t=((b.getAttribute('aria-label')||'')+' '+(b.getAttribute('data-testid')||'')+' '+(b.textContent||'')).toLowerCase();return /attach|upload|add file/.test(t);});if(btn)btn.click();const deadline=Date.now()+1800;while(Date.now()<deadline){inputs=[...document.querySelectorAll('input[type=file]')];input=inputs.find(e=>{const a=(e.getAttribute('accept')||'').toLowerCase();return !a||a.includes('image')||a.includes('*');});if(input)return input;await sleep(25);}return null;}
async function attachBlob(buffer,mime,name){
  const input=await findUploadInput();
  if(!input)throw new Error('ChatGPT upload input not found');
  const doc=input.ownerDocument||document,win=doc.defaultView||window;
  const BlobCtor=win.Blob||Blob,FileCtor=win.File||File,DataTransferCtor=win.DataTransfer||DataTransfer,EventCtor=win.Event||Event,DragEventCtor=win.DragEvent||DragEvent;
  const blob=new BlobCtor([buffer],{type:mime||'image/jpeg'});const file=new FileCtor([blob],name||'ai-snap.jpg',{type:blob.type||'image/jpeg',lastModified:Date.now()});
  let lastError=null;
  try{const transfer=new DataTransferCtor();transfer.items.add(file);const setter=Object.getOwnPropertyDescriptor(win.HTMLInputElement?.prototype||HTMLInputElement.prototype,'files')?.set;if(!setter)throw new Error('ChatGPT file input setter unavailable');setter.call(input,transfer.files);input.dispatchEvent(new EventCtor('input',{bubbles:true,composed:true}));input.dispatchEvent(new EventCtor('change',{bubbles:true,composed:true}));await sleep(100);if(input.files?.length)return true;}catch(e){lastError=e;}
  try{const transfer=new DataTransferCtor();transfer.items.add(file);input.files=transfer.files;input.dispatchEvent(new EventCtor('input',{bubbles:true,composed:true}));input.dispatchEvent(new EventCtor('change',{bubbles:true,composed:true}));await sleep(100);if(input.files?.length)return true;}catch(e){lastError=e;}
  try{const target=[...doc.querySelectorAll('[contenteditable="true"],textarea')].find(visible)||doc.activeElement;if(target){const transfer=new DataTransferCtor();transfer.items.add(file);target.dispatchEvent(new DragEventCtor('drop',{bubbles:true,cancelable:true,composed:true,dataTransfer:transfer}));await sleep(250);return true;}}catch(e){lastError=e;}
  try{await navigator.clipboard.write([new ClipboardItem({[blob.type||'image/png']:blob})]);alert('AI Snap: image copied. Press Ctrl+V in ChatGPT to paste it.');return true;}catch(e){lastError=e;}
  throw new Error(`ChatGPT attachment failed: ${lastError?.message||'the ChatGPT upload control rejected the image'}`);
}
async function fetchFileThroughExtension(url,metaUrl,eventMeta={}){for(let attempt=0;attempt<6;attempt++){try{const r=await runtimeMessage({type:'AI_SNAP_FETCH_FILE',url,metaUrl,eventMeta});if(r?.ok)return r;if(r?.status===404){await sleep(100);continue}return r||{ok:false,error:'No response'};}catch(e){if(contextDead)throw e;if(attempt===5)throw e;await sleep(100);}}return {ok:false,status:404,error:'File not available yet'};}
async function deliver(name,eventMeta={}){if(!isCurrentChat()||processing.has(name))return false;processing.add(name);let stage='starting';try{const c=await getConfig(),base=(c.baseUrl||'').replace(/\/$/,'');if(!c.enabled||!base||!c.pairCode||!c.privateKey)throw new Error('Secure pairing is not configured.');stage='downloading encrypted image';const url=`${base}/api/file/${encodeURIComponent(name)}?code=${encodeURIComponent(c.pairCode)}`;const metaUrl=`${base}/api/file-meta?code=${encodeURIComponent(c.pairCode)}&name=${encodeURIComponent(name)}`;const r=await fetchFileThroughExtension(url,metaUrl,eventMeta);if(!r?.ok)throw new Error(r?.status?`Could not download encrypted image (${r.status}).`:(r?.error||'Could not download encrypted image.'));stage='reading encryption metadata';const h=r.headers||{};const iv=h['X-AI-Snap-IV']||eventMeta.iv||'',wrapped=h['X-AI-Snap-Key']||eventMeta.wrappedKey||'',mime=h['X-AI-Snap-Mime']||eventMeta.mime||'image/jpeg',original=h['X-AI-Snap-Name']||eventMeta.originalName||'ai-snap.jpg';if(!iv||!wrapped)throw new Error('Encrypted metadata is missing.');if(!(r.data instanceof ArrayBuffer))throw new Error('Encrypted image data is invalid.');const encrypted=r.data;stage='unwrapping AES key';let privateKey;try{privateKey=await crypto.subtle.importKey('jwk',c.privateKey,{name:'RSA-OAEP',hash:'SHA-256'},false,['decrypt']);}catch(e){throw new Error(`RSA private key is invalid: ${e?.name||'DOMException'}. Create a new secure pairing.`)}let rawAes;try{rawAes=await crypto.subtle.decrypt({name:'RSA-OAEP'},privateKey,fromB64url(wrapped));}catch(e){throw new Error(`RSA key unwrap failed: ${e?.name||'DOMException'}. Create a new secure pairing.`)}const aesKey=await crypto.subtle.importKey('raw',rawAes,{name:'AES-GCM'},false,['decrypt']);stage='decrypting image data';let plain;try{plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:fromB64url(iv)},aesKey,encrypted);}catch(e){throw new Error(`AES-GCM decrypt failed: ${e?.name||'DOMException'}. The encrypted image or metadata does not match.`)}stage='attaching image to ChatGPT';await attachBlob(plain,mime,original);runtimeMessage({type:'AI_SNAP_ACK',url:`${base}/api/ack?code=${encodeURIComponent(c.pairCode)}`,method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name})}).catch(()=>{});return true;}catch(e){if(!contextDead)console.error(`AI Snap: ${stage}:`,e);return false;}finally{processing.delete(name);}}
async function checkPending(){if(!isCurrentChat()||pendingCheckInFlight)return;pendingCheckInFlight=true;try{const c=await getConfig(),base=(c.baseUrl||'').replace(/\/$/,'');if(!c.enabled||!base||!c.pairCode||!c.privateKey)return;const r=await runtimeMessage({type:'AI_SNAP_FETCH_PENDING',url:`${base}/api/pending?code=${encodeURIComponent(c.pairCode)}`});if(!r?.ok)return;const d=JSON.parse(r.text||'{}');for(const f of(Array.isArray(d.files)?d.files:[]))await deliver(f.name);}catch(e){if(!contextDead&&!/context invalidated/i.test(e?.message||''))console.error('AI Snap pending check:',e);}finally{pendingCheckInFlight=false;}}
function safeCheckPending(){checkPending().catch(()=>{});}
function startPolling(){if(pollTimer)clearInterval(pollTimer);pollTimer=setInterval(()=>{if(isCurrentChat())safeCheckPending();},250);safeCheckPending();}
function connectEvents(){if(contextDead)return;if(eventSource){eventSource.close();eventSource=null}if(reconnectTimer)clearTimeout(reconnectTimer);getConfig().then(c=>{if(contextDead)return;const base=(c.baseUrl||'').replace(/\/$/,'');if(!c.enabled||!base||!c.pairCode||!c.privateKey)return;try{eventSource=new EventSource(`${base}/api/events?code=${encodeURIComponent(c.pairCode)}`);eventSource.onmessage=e=>{try{const d=JSON.parse(e.data);if(d.name&&isCurrentChat())deliver(d.name,{iv:d.iv||'',wrappedKey:d.wrappedKey||'',mime:d.mime||'',originalName:d.originalName||''}).catch(()=>{});}catch(_){}};eventSource.onerror=()=>{if(contextDead)return;if(eventSource){eventSource.close();eventSource=null}reconnectTimer=setTimeout(connectEvents,700);};}catch(_){reconnectTimer=setTimeout(connectEvents,700);}}).catch(()=>{});}
function cleanup(){if(pollTimer){clearInterval(pollTimer);pollTimer=null}if(reconnectTimer){clearTimeout(reconnectTimer);reconnectTimer=null}if(eventSource){try{eventSource.close();}catch(_){ }eventSource=null}if(observer){try{observer.disconnect();}catch(_){ }observer=null;}}
chrome.runtime.onMessage.addListener(message=>{if(contextDead)return;if(message?.type==='AI_SNAP_ACTIVE_STATE'){activeTab=!!message.active;if(activeTab)safeCheckPending();}});
async function init(){try{const r=await runtimeMessage({type:'AI_SNAP_GET_ACTIVE_STATE'});activeTab=!!r?.active;}catch(e){if(contextDead)return;activeTab=document.visibilityState==='visible'}startPolling();connectEvents();}
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'){safeCheckPending();connectEvents();}});
observer=new MutationObserver(()=>{if(activeTab&&document.visibilityState==='visible')safeCheckPending();});observer.observe(document.documentElement,{childList:true,subtree:true});init().catch(()=>{});
