const $=id=>document.getElementById(id),list=$('list'),status=$('status');
function dbOpen(){return new Promise((resolve,reject)=>{const r=indexedDB.open('orami-history',1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains('files'))r.result.createObjectStore('files',{keyPath:'id'});};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error||new Error('Could not open local History'));});}
function allFiles(db){return new Promise((resolve,reject)=>{const r=db.transaction('files','readonly').objectStore('files').getAll();r.onsuccess=()=>resolve((r.result||[]).sort((a,b)=>(b.createdAt||0)-(a.createdAt||0)));r.onerror=()=>reject(r.error);});}
function removeFile(db,id){return new Promise((resolve,reject)=>{const tx=db.transaction('files','readwrite');tx.objectStore('files').delete(id);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});}
function clearAll(db){return new Promise((resolve,reject)=>{const tx=db.transaction('files','readwrite');tx.objectStore('files').clear();tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});}
function bytesToBlob(data,mime){return new Blob([data],{type:mime||'application/octet-stream'});}
function sizeText(n){if(n<1024)return n+' B';if(n<1048576)return (n/1024).toFixed(1)+' KB';return (n/1048576).toFixed(1)+' MB';}
function formatDate(t){try{return new Date(t).toLocaleString()}catch{return 'Received file'}}
function addButton(parent,label,cls,fn){const b=document.createElement('button');b.textContent=label;if(cls)b.className=cls;b.addEventListener('click',fn);parent.appendChild(b);return b;}
async function render(){status.textContent='Loading local files…';list.replaceChildren();let db;try{db=await dbOpen();let rows=await allFiles(db);const cutoff=Date.now()-7*24*60*60*1000,expired=rows.filter(row=>(row.createdAt||0)<cutoff);if(expired.length){await new Promise((resolve,reject)=>{const tx=db.transaction('files','readwrite'),store=tx.objectStore('files');for(const row of expired)store.delete(row.id);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});rows=rows.filter(row=>(row.createdAt||0)>=cutoff);}status.textContent=rows.length+' file'+(rows.length===1?'':'s')+' in local History';if(!rows.length){const empty=document.createElement('div');empty.className='empty';empty.textContent='No received files yet. Send a photo or document from your phone while an AI chat tab is open.';list.appendChild(empty);return;}
for(const row of rows){const blob=bytesToBlob(row.data,row.mime),url=URL.createObjectURL(blob),card=document.createElement('article');card.className='item';const preview=document.createElement('div');preview.className='preview';if((row.mime||'').startsWith('image/')){const img=document.createElement('img');img.src=url;img.alt=row.name||'Received image';preview.appendChild(img);}else if(row.mime==='application/pdf'){const iframe=document.createElement('iframe');iframe.src=url+'#toolbar=0';iframe.title=row.name||'PDF preview';preview.appendChild(iframe);}else{const icon=document.createElement('div');icon.className='fileIcon';icon.textContent=(row.name||'').toLowerCase().endsWith('.csv')?'▦':(row.name||'').toLowerCase().endsWith('.txt')?'≡':'📄';preview.appendChild(icon);}
const info=document.createElement('div');info.className='info';const name=document.createElement('div');name.className='name';name.textContent=row.name||'Received file';const meta=document.createElement('div');meta.className='meta';meta.textContent=[row.site||'AI chat',formatDate(row.createdAt),sizeText(row.data?.byteLength||0)].join(' · ');const actions=document.createElement('div');actions.className='itemActions';addButton(actions,'Download','primary',()=>{const a=document.createElement('a');a.href=url;a.download=row.name||'orami-file';document.body.appendChild(a);a.click();a.remove();});addButton(actions,'Delete','',async()=>{await removeFile(db,row.id);URL.revokeObjectURL(url);render();});info.append(name,meta,actions);card.append(preview,info);list.appendChild(card);}
}catch(e){status.textContent='Could not load History: '+(e.message||e);}finally{db?.close();}}
$('refresh').addEventListener('click',render);$('clear').addEventListener('click',async()=>{if(!confirm('Delete every file in Orami History? This cannot be undone.'))return;let db;try{db=await dbOpen();await clearAll(db);await render();}catch(e){status.textContent='Could not clear History: '+(e.message||e);}finally{db?.close();}});render();