const BASE_URL='https://ai-snap-cloud-production.up.railway.app';
const $=id=>document.getElementById(id);const baseInput=$('baseUrl'),saveButton=$('save'),pairButton=$('pair'),newPairButton=$('newPair'),copyButton=$('copy'),status=$('status'),pairBox=$('pairBox'),codeInput=$('code'),mobileUrl=$('mobileUrl'),qr=$('qr');
function setStatus(m,ok=false){status.textContent=m;status.className=ok?'ok':'bad'}
async function getConfig(){return chrome.storage.local.get({baseUrl:BASE_URL,pairCode:'',enabled:true,privateKey:null,publicKey:null});}
async function setConfig(v){return chrome.storage.local.set(v);}
async function createKeyPair(){const keys=await crypto.subtle.generateKey({name:'RSA-OAEP',modulusLength:2048,publicExponent:new Uint8Array([1,0,1]),hash:'SHA-256'},true,['encrypt','decrypt']);return {publicKey:await crypto.subtle.exportKey('jwk',keys.publicKey),privateKey:await crypto.subtle.exportKey('jwk',keys.privateKey)};}
function showPairing(base,code){const clean=base.replace(/\/$/,'');codeInput.value=code;mobileUrl.textContent=`${clean}/mobile/?code=${encodeURIComponent(code)}`;qr.src=`${clean}/api/pair/qr?code=${encodeURIComponent(code)}&t=${Date.now()}`;qr.style.display='block';pairBox.classList.add('show');}
async function createPairing(){const base=(baseInput.value||BASE_URL).trim().replace(/\/$/,'');if(!/^https?:\/\//i.test(base)){setStatus('Use a full URL starting with https://');return;}setStatus('Creating secure pairing…');try{const keys=await createKeyPair();const r=await fetch(`${base}/api/pair/create`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({publicKey:keys.publicKey}),cache:'no-store'});const d=await r.json();if(!r.ok||!d.ok||!d.e2ee)throw new Error(d.error||'Could not create pairing');await setConfig({baseUrl:base,pairCode:d.code,enabled:true,privateKey:keys.privateKey,publicKey:keys.publicKey});showPairing(base,d.code);setStatus('✓ New secure E2EE pairing created. Scan the QR code or enter the code.',true);}catch(e){console.error(e);setStatus(e.message||'Could not create pairing');}}
(async()=>{const c=await getConfig();baseInput.value=c.baseUrl||BASE_URL;if(c.pairCode&&c.privateKey){try{const base=(c.baseUrl||BASE_URL).replace(/\/$/,'');const r=await fetch(`${base}/api/pair/status?code=${encodeURIComponent(c.pairCode)}`,{cache:'no-store'});const d=await r.json();if(r.ok&&d.ok&&d.e2ee&&d.publicKey){showPairing(base,c.pairCode);setStatus('✓ E2EE pairing is active.',true);}else setStatus('Pairing expired. Create a new one.');}catch(_){setStatus('Server is unreachable. The saved pairing was kept.');}}})();
saveButton.addEventListener('click',async()=>{const base=baseInput.value.trim().replace(/\/$/,'');if(!/^https?:\/\//i.test(base)){setStatus('Use a full URL starting with https://');return;}try{const r=await fetch(`${base}/health`,{cache:'no-store'}),d=await r.json();if(!r.ok||!d.ok)throw 0;await setConfig({baseUrl:base});setStatus('✓ Server saved and reachable.',true);}catch(_){setStatus('Could not reach that server URL.');}});pairButton.addEventListener('click',createPairing);newPairButton.addEventListener('click',createPairing);copyButton.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(mobileUrl.textContent);setStatus('✓ Phone link copied.',true);}catch(_){setStatus('Copy failed — select the link instead.');}});
